version: "3"

volumes:
  db-data:
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/product-register"
    tty: true
    stdin_open: true
    environment:
      - "POSTGRES_PASSWORD=postgres"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - "db-data:/var/lib/postgresql/data"
